using BankingSimulation.Data.Database;
using BankingSimulation.Data.Entities;
using Microsoft.EntityFrameworkCore;

namespace BankingSimulation.Data.Repositories;

public class AccountRepository(BankingDbContext db) : IAccountRepository
{
    public Task<Account?> GetByIdAsync(long id) =>
        db.Accounts.Include(a => a.Owner).FirstOrDefaultAsync(a => a.Id == id);

    public Task<Account?> GetByNumberAsync(string accountNumber) =>
        db.Accounts.Include(a => a.Owner).FirstOrDefaultAsync(a => a.AccountNumber == accountNumber);

    public async Task<IEnumerable<Account>> GetByOwnerIdAsync(long ownerId) =>
        await db.Accounts.Include(a => a.Owner).Where(a => a.OwnerId == ownerId).ToListAsync();

    public async Task<IEnumerable<Account>> GetAllAsync() =>
        await db.Accounts.Include(a => a.Owner).ToListAsync();

    public async Task<Account> CreateAsync(Account account)
    {
        // Account IDs are generated by SQL Server and are globally unique.
        // Use a temporary unique value for the insert, then derive the public
        // account number from the generated ID. The transaction prevents a
        // partially-created account if the second save fails.
        await using var transaction = db.Database.IsRelational()
            ? await db.Database.BeginTransactionAsync()
            : null;

        account.AccountNumber = Guid.NewGuid().ToString("N");
        db.Accounts.Add(account);
        await db.SaveChangesAsync();

        account.AccountNumber = $"ACC{account.Id:D10}";
        await db.SaveChangesAsync();

        if (transaction is not null)
            await transaction.CommitAsync();

        return account;
    }

    public async Task UpdateAsync(Account account)
    {
        db.Accounts.Update(account);
        await db.SaveChangesAsync();
    }
}
